### PR TITLE
updating map style + location

### PR DESCRIPTION
**Pull request by htmlandbacon**
Had a few issues with mapbox + caching.

This upgrades to mapbox-gl

Also followed this for creating the data https://www.mapbox.com/help/add-points-pt-1/

screen shot 2018-06-25 at 21 40 25

The can all be controlled via mapbox in theory!

### CODE REVIEW

**Comment by samdbeckham** [comment]
Not sure about having the logo as the marker. I like the general idea, but I think a regular marker is a lot more clear as to what's going on.

I can't tell from the screenshot, but clicking on the marker in the original map brings up the address as a tooltip. Does this one do the same? 
image

**Comment by htmlandbacon** [comment]
You can customize the marker in mapbox,

Seems you can in part 3 https://www.mapbox.com/help/add-points-pt-3/ - will take a look later

**Comment by htmlandbacon** [comment]
Updated style and added marker! 🔥

screen shot 2018-06-26 at 19 08 58

**Review by tempertemper — APPROVED** [review]
LGTM

**Pull request merged**
